URI: "bolt://localhost:7687"
USER: "neo4j"
PASS: ''

nodes:
  - csvname: 'node_track.csv'
    label: 'Track'
    properties:
      spotify_id: 'spotify_id'
      name: 'name'
      popularity: 'popularity'
      streams: 'streams'
      release_date: 'release_date'
      # length: 'duration_ms'
      # key: 'key'
      # mode: 'mode'    

  - csvname: 'node_artist.csv'
    label: 'Artist'
    properties:
      spotify_id: 'spotify_id'
      name: 'name'
      followers: 'followers'
      popularity: 'popularity'

  - csvname: 'node_genre.csv'
    label: 'Genre'
    properties:
      name: 'genres'

  - csvname: 'node_playlist.csv'
    label: 'Playlist'
    properties:
      spotify_id: 'id'
      name: 'name'
      description: 'description'

  - csvname: 'node_feature.csv'
    label: 'AudioFeature'
    properties:
      #feature_id: 'feature_id'
      name: 'name'
      feature_name: 'feature'
      grouping: 'encoding'

edges:
  - csvname: 'edge_track_artist.csv'
    label: 'PERFORMS'
    properties: {}
    from_label: 'Artist'
    from_id: 'spotify_id' 
    from_col: 'artist'
    to_label: 'Track'
    to_id: 'spotify_id' 
    to_col: 'track'

  - csvname: 'edge_artist_genre.csv'
    label: 'CATEGORIZED_AS'
    properties: {}
    from_label: 'Artist'
    from_id: 'spotify_id'
    from_col: 'artist'
    to_label: 'Genre'
    to_id: 'name'
    to_col: 'genres'

  - csvname: 'edge_playlist_track.csv'
    label: 'CONTAINS_TRACK'
    properties: 
       added_at: 'added_at'
    from_label: 'Playlist'
    from_id: 'spotify_id'
    from_col: 'playlist_id'
    to_label: 'Track'
    to_id: 'spotify_id'
    to_col: 'track_id'

  - csvname: 'edge_track_feature.csv'
    label: 'AUDIO_FEATURE'
    properties: 
      feature: 'feature'
      encoding: 'encoding'
      value: 'value'
    from_label: 'Track'
    from_id: 'spotify_id'
    from_col: 'spotify_id'
    to_label: 'AudioFeature'
    to_id: 'name'
    to_col: 'name'