URI: "bolt://localhost:7687"
USER: "neo4j"
PASS: ''

nodes:
  - csvname: 'node_track.csv'
    label: 'Track'
    properties:
      spotify_id: 'spotify_id'
      name: 'name'
      popularity: 'popularity'
      streams: 'streams'
      release_date: 'release_date' 

  - csvname: 'node_artist.csv'
    label: 'Artist'
    properties:
      spotify_id: 'spotify_id'
      name: 'name'
      followers: 'followers'
      popularity: 'popularity'

  - csvname: 'node_genre.csv'
    label: 'Genre'
    properties:
      name: 'genres'

  - csvname: 'node_playlist.csv'
    label: 'Playlist'
    properties:
      spotify_id: 'id'
      name: 'name'
      description: 'description'

  - csvname: 'node_feature.csv'
    label: 'AudioFeature'
    properties:
      name: 'name'
      feature_name: 'feature'
      grouping: 'encoding'

  - csvname: 'node_keywords.csv'
    label: 'Keyword'
    properties: 
      name: 'word'

  - csvname: 'node_topic.csv'
    label: 'Topic'
    properties:
      name: 'topic'
      topic_id: 'topic_id'

edges:
  - csvname: 'edge_track_artist.csv'
    label: 'PERFORMS'
    properties: {}
    from_label: 'Artist'
    from_id: 'spotify_id' 
    from_col: 'artist'
    to_label: 'Track'
    to_id: 'spotify_id' 
    to_col: 'track'

  - csvname: 'edge_artist_genre.csv'
    label: 'CATEGORIZED_AS'
    properties: {}
    from_label: 'Artist'
    from_id: 'spotify_id'
    from_col: 'artist'
    to_label: 'Genre'
    to_id: 'name'
    to_col: 'genres'

  - csvname: 'edge_playlist_track.csv'
    label: 'CONTAINS_TRACK'
    properties: 
       added_at: 'added_at'
    from_label: 'Playlist'
    from_id: 'spotify_id'
    from_col: 'playlist_id'
    to_label: 'Track'
    to_id: 'spotify_id'
    to_col: 'track_id'

  - csvname: 'edge_track_feature.csv'
    label: 'AUDIO_FEATURE'
    properties: 
      feature: 'feature'
      encoding: 'encoding'
      value: 'value'
    from_label: 'Track'
    from_id: 'spotify_id'
    from_col: 'spotify_id'
    to_label: 'AudioFeature'
    to_id: 'name'
    to_col: 'name'

  - csvname: 'edge_word_topic.csv'
    label: 'BELONGS_TO'
    properties:
      probability: 'probability'
    from_label: 'Keyword'
    from_id: 'name'
    from_col: 'word'
    to_label: 'Topic'
    to_id: 'topic_id'
    to_col: 'topic_id'

  - csvname: 'edge_word_track.csv'
    label: 'CONTAINS_KEYWORD'
    properties:
      occurence: 'occurence'
    from_label: 'Track'
    from_id: 'spotify_id'
    from_col: 'sid'
    to_label: 'Keyword'
    to_id: 'name'
    to_col: 'word'